### ISSUE TITLE
[1.11.2][Infernal Mobs] NPE when rendering overlay

### ISSUE THREAD

**Issue by AGSPhoenix** [AtomicStryker/atomicstrykers-minecraft-mods#105]
Here are the highlights:
~~~
java.lang.NullPointerException: Unexpected error
	at atomicstryker.infernalmobs.common.MobModifier.getEntityDisplayName(MobModifier.java:402)
	at atomicstryker.infernalmobs.client.InfernalMobsClient.onPreRenderGameOverlay(InfernalMobsClient.java:118)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_109_InfernalMobsClient_onPreRenderGameOverlay_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:885)
	at net.minecraftforge.client.GuiIngameForge.renderBossHealth(GuiIngameForge.java:239)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:147)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
~~~
Here's the full crash report: [crash-2017-05-05_20.34.31-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/980619/crash-2017-05-05_20.34.31-client.txt)

There are several other mods in this pack that add custom mobs. Not sure if those are doing any weird things that are causing Infernal Mobs to trip up. The crash is fairly infrequent for me, although it's happening to one of my friends about every 30 minutes on average.

Let me know if you need any more information or if there's anything you'd like me to test. I've dabbled in Forge mod development before, so I might be able to reproduce this in a development environment.

**Comment by AtomicStryker** [comment]
This appears to be something i fixed months ago https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/a13d115d2abb4ce49214892a3647498171de92c0#diff-9d9a78d85bc8b04b1c2846b74876913b ... did i forget to push this to the repositories? Maybe. I pushed the up to date jar to the outlets again - grab it here https://github.com/AtomicStryker/github.io/blob/master/files/1.11.2/InfernalMobs-1.11.2.jar

**Comment by AtomicStryker** [comment]
And thank you for notifying me

**Comment by AGSPhoenix** [comment]
Checked the source files in the jar you linked and the one I have, and that diff you linked is the only difference in MobModifier.java, so you're probably right. Thanks for the updated jar.
