### ISSUE TITLE
Incompatibility with Embers

### ISSUE THREAD

**Issue by leagris** [AtomicStryker/atomicstrykers-minecraft-mods#120]
using:

- forge-1.11.2-13.20.0.2315-universal
- embers-0.216
- MultiMine-1.11.2-1.5.7

Anordinarymoose wrote on June 26, 2017 11:43 PM CET
> when i try to break an alchemy table it either duplicates and doesent break or it crashes me

https://pastebin.com/L6WezEyj
```
java.lang.NullPointerException: Unexpected error
    at teamroots.embers.block.BlockAlchemyPedestal.func_176208_a(BlockAlchemyPedestal.java:105)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1127)
    at atomicstryker.multimine.client.MultiMineClient.updateLocalPartialBlock(MultiMineClient.java:224)
    at atomicstryker.multimine.client.MultiMineClient.eventPlayerDamageBlock(MultiMineClient.java:131)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:309)
    at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1422)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2193)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

See:
- https://github.com/RootsTeam/Embers/issues/216

**Comment by leagris** [comment]
Unrelated to multimine

**Comment by AtomicStryker** [comment]
Generic debugging advice: If you read the stack trace and there is minecraft code between the crash and the last line of a different mod (compared to the crashing one) it is usually unrelated. Usually does not mean always, though :)
