### ISSUE TITLE
[bug] pet bat - server crash with NullPointerException

### ISSUE THREAD

**Issue by DanTheColoradan** [AtomicStryker/atomicstrykers-minecraft-mods#18]
I'm not sure it is the flute, but if I throw it out of my inventory, the server definitely crashes. Here is the crash report:

https://gist.github.com/DanTheColoradan/f5ce0cabd134bb84a611

**Comment by DanTheColoradan** [comment]
Cancel that. It's not the flute. Hmm. Potentially here?

```
Entity's Rider: ~~ERROR~~ NullPointerException: null
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```

**Comment by AtomicStryker** [comment]
It is Pet Bat, however it crashes because your minecraft is missing a 
known method. Try updating forge?

**Comment by DanTheColoradan** [comment]
Updated to MinecraftForge v11.14.3.1487 and tried again. Crashed with:

```
[11:01:26] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:710) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.IChatComponent.func_150254_d()Ljava/lang/String;
	at atomicstryker.petbat.common.ItemPocketedPetBat.fromBatEntity(ItemPocketedPetBat.java:59) ~[ItemPocketedPetBat.class:?]
	at atomicstryker.petbat.common.EntityPetBat.func_70071_h_(EntityPetBat.java:407) ~[EntityPetBat.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1880) ~[aqu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732) ~[qt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1850) ~[aqu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1679) ~[aqu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571) ~[qt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by DanTheColoradan** [comment]
Also tried it with MinecraftForge v11.14.3.1450. Also crashed. It looks like the same error.

**Comment by AtomicStryker** [comment]
Augh, blast me for not checking your versions. PetBat 1.3.8 has a fix for this very issue. Kindly use the latest version.

**Comment by DanTheColoradan** [comment]
Thank you very much. Sorry I didn't have the latest version. I downloaded what I thought was the latest from forge :-/

Thanks again! :+1:
