### ISSUE TITLE
Incredible lag that makes the game unplayable.

### ISSUE THREAD

**Issue by Rencer** [AtomicStryker/atomicstrykers-minecraft-mods#187]
Im playing with MC 1.12.2.
This bug makes the game unplayable because of the lag.

Millions of this kind of message in the log:

[Server thread/WARN] [FML]: Ruins Mod loaded a new chunk (17, 1  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker.
Here it is. I reported it.

And literally non-stop spamming the log whit EXACTLY this message over and over again:

[12:54:20] [Thread-221/INFO] [STDERR]: [atomicstryker.ruins.common.RuinGenerator$FlushThread:run:142]: java.io.IOException: No such file or directory
[12:54:20] [Thread-221/INFO] [STDERR]: [atomicstryker.ruins.common.RuinGenerator$FlushThread:run:142]: 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:54:20] [Thread-221/INFO] [STDERR]: [atomicstryker.ruins.common.RuinGenerator$FlushThread:run:142]: 	at java.io.File.createNewFile(File.java:1012)
[12:54:20] [Thread-221/INFO] [STDERR]: [atomicstryker.ruins.common.RuinGenerator$FlushThread:run:142]: 	at atomicstryker.ruins.common.RuinGenerator$FlushThread.run(RuinGenerator.java:98)

**Comment by AtomicStryker** [comment]
Hmm yes i suppose this would happed if Ruins continuously fails to create the file ".minecraft\saves\**RUNNINGWORLDNAME**\RuinsPositionsFile.txt". I can see you appear to be on Linux. Does the minecraft application perhaps do not have write access to that folder or something? Try creating the file by hand?

**Comment by Rencer** [comment]
I'm using MultiMC and when I checked the folders permissions, it turned out that I have r&w permission but the "group" not. I didn't noticed it, when made the instance. I think MultiMC set the folders permissions incorretly.
So, that was the problem, changing the folder permissions fixed it.
Thanks!
