### ISSUE TITLE
Ruins + Mystcraft + Secret Rooms = combo bug :D

### ISSUE THREAD

**Issue by Darkos333** [AtomicStryker/atomicstrykers-minecraft-mods#22]
This one's really interesting...
So, I am getting lots of theese after including Ruins in my modpack:

[23:44:19] [Server thread/DEBUG] [com.github.abrarsyed.secretroomsmod.common.OwnershipManager/]: Saving ownership data for dimension 69 to C:\Users\Darkos\AppData\Roaming.minecraft\saves\Test\DIM69\SecretRooms-ownership.dat
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: C:\Users\Darkos\AppData\Roaming.minecraft\saves\mystcraft_profiling\DIM69\RuinsPositionsFile.txt_writing (System nie może odnaleźć określonej ścieżki)
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.io.FileOutputStream.open(Native Method)
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.io.FileWriter.<init>(FileWriter.java:90)
[23:44:19] [Thread-5990/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.run(RuinGenerator.java:88)

Theese prints appear immediately after each other. Every time this log block appears my game freezes for around half second, then unfreezes for a second (until next block of logs appears in the console). This happens whole the time - it iterates through all dimensions the save posses and repeats the cycle. It happens both on old and fresh saves. Reproduced with and without FastCraft.

Full log: http://www49.zippyshare.com/v/Ulg2jGn7/file.html

Ps: "System nie może odnaleźć określonej ścieżki" is a polish equivalent to java's message: "The system cannot find the path specified"

**Comment by AtomicStryker** [comment]
Well, are there restrictions in place preventing Ruins from creating that file? Have you tried creating that file yourself?

**Comment by Darkos333** [comment]
Well "RuinsPositionsFile.txt_writing"... I can manually create this file in the specified path (tried just now), but... dont you think "txt_writing" is rather unusual extension?
Especially since "RuinsPositionsFile.txt" is already there.

**Comment by AtomicStryker** [comment]
It's so you won't have an empty file if MC or Ruins crashes while writing it. RuinsPositionsFile.txt_writing is in process of being written, upon completion RuinsPositionsFile.txt is deleted and ..._writing is renamed to it.

**Comment by Darkos333** [comment]
OK, I got the idea behind this.
WHOAH, WAIT: I've found it!
To myself: Next time when you test if file can be written under specific location, copy-paste the path instead of going there manually / using shortcuts.
So, back on the track:
There is small derp in path to a file: C:\Users\Darkos\AppData\Roaming.minecraft\saves\Test\DIM69\
Notice missing backslash between Roaming and .minecraft.

**Comment by AtomicStryker** [comment]
Are you sure that didnt happen when copy pasting? The save folder reader is one of those things in the mod which never broke before

**Comment by Darkos333** [comment]
Oh crap, you are right. Missing backslash magically evaporated during copy-pasting :/
Just checked the log file - backslash is there.
It requires a bit more testing which cant be done now, but it looks like shutting down my AV prevents this bug from occurence.

**Comment by AtomicStryker** [comment]
Then i suggest you add your entire mc folder to the exclusion list, so that i can push trojans and viruses down your throat unopposed >:D
