### ISSUE TITLE
ruins mod 1.13.2 does not work in minecraft server 

### ISSUE THREAD

**Issue by icecloud80** [AtomicStryker/atomicstrykers-minecraft-mods#257]
it throws null pointer exception when running the server

Exception caught during firing event: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: atomicstryker.ruins.common.RuinsMod@46f675e9 eventWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V

**Comment by AtomicStryker** [comment]
That stacktrace is incomplete. Given the stacktrace in your curse comment, the actual error is "NoSuchMethodFoundException". You either have a mismatching forge version or there is a coding problem related to standalone servers.

**Comment by icecloud80** [comment]
this is mac version 1.13.2 server and 1.13.2 mod.  here is more stack trace if it helps

`[23:49:48.542] [Server thread/ERROR] [EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: atomicstryker.ruins.common.RuinsMod@5b9839f4 eventWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.getWorldHandle(RuinsMod.java:226)
	at atomicstryker.ruins.common.RuinsMod.eventWorldSave(RuinsMod.java:121)
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_eventWorldSave_Save.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:697)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:275)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Thread.java:745)

[23:49:48.547] [Server thread/ERROR] [MinecraftServer/]: Encountered an unexpected exception
 java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.getWorldHandle(RuinsMod.java:226) ~[?:1.13.2]
	at atomicstryker.ruins.common.RuinsMod.eventWorldSave(RuinsMod.java:121) ~[?:1.13.2]
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_eventWorldSave_Save.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:697) ~[?:?]
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:275) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[23:49:48.553] [Server thread/ERROR] [MinecraftServer/]: This crash report has been saved to: /Users/limo/Documents/mserver/./crash-reports/crash-2019-04-14_23.49.48-server.txt
[23:49:48.553] [Server thread/INFO] [MinecraftServer/]: Stopping server
[23:49:48.557] [Server thread/INFO] [MinecraftServer/]: Saving players
[23:49:48.557] [Server thread/INFO] [MinecraftServer/]: Saving worlds
[23:49:48.557] [Server thread/INFO] [MinecraftServer/]: Saving chunks for level 'mo_world'/minecraft:the_end
[23:49:48.557] [Server thread/ERROR] [EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: atomicstryker.ruins.common.RuinsMod@5b9839f4 eventWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.getWorldHandle(RuinsMod.java:226)
	at atomicstryker.ruins.common.RuinsMod.eventWorldSave(RuinsMod.java:121)
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_eventWorldSave_Save.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:697)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:483)
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:512)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:601)
	at java.lang.Thread.run(Thread.java:745)

[23:49:48.558] [Server thread/ERROR] [MinecraftServer/]: Exception stopping the server
 java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.getWorldHandle(RuinsMod.java:226) ~[?:1.13.2]
	at atomicstryker.ruins.common.RuinsMod.eventWorldSave(RuinsMod.java:121) ~[?:1.13.2]
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_eventWorldSave_Save.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:483) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:512) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:601) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[23:49:48.559] [Server Shutdown Thread/INFO] [MinecraftServer/]: Stopping server
[23:49:48.560] [Server Shutdown Thread/INFO] [MinecraftServer/]: Saving players
[23:49:48.560] [Server Shutdown Thread/INFO] [MinecraftServer/]: Saving worlds
[23:49:48.560] [Server Shutdown Thread/INFO] [MinecraftServer/]: Saving chunks for level 'mo_world'/minecraft:the_end
[23:49:48.560] [Server Shutdown Thread/ERROR] [EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: atomicstryker.ruins.common.RuinsMod@5b9839f4 eventWorldSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.getWorldHandle(RuinsMod.java:226)
	at atomicstryker.ruins.common.RuinsMod.eventWorldSave(RuinsMod.java:121)
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_eventWorldSave_Save.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:697)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:483)
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:512)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:884)

[23:49:48.560] [Server Shutdown Thread/ERROR] [MinecraftServer/]: Caught previously unhandled exception :
[23:49:48.561] [Server Shutdown Thread/ERROR] [MinecraftServer/]: java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
logout
`

**Comment by AtomicStryker** [comment]
I will try to start a dedi server this weekend maybe... busy

**Comment by AtomicStryker** [comment]
My apologies, i had sort of forgotten about this.
Have a bugfix! https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/96717dc3ddfd8a7d0341cd522517bbd487fc953f

I will push the fixed jar to curse and the IO repository of mine shortly.
