### ISSUE TITLE
could not find any blockstates in rule 2,98,log-1

### ISSUE THREAD

**Issue by Bitmxp** [AtomicStryker/atomicstrykers-minecraft-mods#268]
When I run my Minecraft Dedicated Server (v1.13.2)

I get this type of error in the console (a LOT of them):
could not find any blockstates in rule 2,98,log-1
could not find any blockstates in rule 0,100,log-3

I'm using Forge and I put the .jar in the /mods/ folder and placed ruins_config in the /config/ folder

![image](https://user-images.githubusercontent.com/48726812/60387110-8375a880-9a53-11e9-88f1-86a02be7a438.png)

Then, when I join my own world, the server crashes.

The crash log is:
```---- Minecraft Crash Report ----
// Sorry :(

Time: 6/29/19 9:53 AM
Description: Exception generating new chunk

java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_211] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_211] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.storage.WorldInfo.func_202836_i()I
	at atomicstryker.ruins.common.RuinsMod.onReplaceBiomeBlocks(RuinsMod.java:204) ~[?:1.13.2] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_10_RuinsMod_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.9.2-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:254) ~[eventbus-0.9.2-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onReplaceBiomeBlocks(ForgeEventFactory.java:643) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.AbstractChunkGenerator.func_205471_a(AbstractChunkGenerator.java:109) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_202088_a(ChunkGeneratorOverworld.java:83) ~[?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.tasks.BaseChunkTask.func_202840_a(SourceFile:13) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.tasks.ChunkTask.func_202839_a(SourceFile:35) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.ChunkStatus.func_202126_a(SourceFile:95) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.tasks.ProtoChunkScheduler.func_201493_a_(ProtoChunkScheduler.java:77) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.tasks.ProtoChunkScheduler.func_201493_a_(ProtoChunkScheduler.java:26) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Scheduler$FutureWrapper.func_202912_a(SourceFile:147) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_201722_a(ChunkProviderServer.java:146)

-- Chunk to be generated --
Details:
	Location: -10,23
	Position hash: 103079215094
	Generator: net.minecraft.world.gen.ChunkGeneratorOverworld@5fe6a88
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_201722_a(ChunkProviderServer.java:146)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:117)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:105)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:123)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:201)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:738)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:565)
	at java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Bxtterman'/300, l='world', x=-147.02, y=95.40, z=208.60]]
	Chunk stats: ServerChunkCache: 657 Drop: 0
	Level seed: 4007241142197557611
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (40,87,13), Chunk: (at 8,5,13 in 2,0; contains blocks 32,0,0 to 47,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 811924 game time, 1218 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3100845528 bytes (2957 MB) / 4039114752 bytes (3852 MB) up to 4039114752 bytes (3852 MB)
	JVM Flags: 2 total; -Xmx4G -Xms4G
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Bxtterman'/300, l='world', x=-147.02, y=95.40, z=208.60]]
	Data Packs: mod:ruins, mod:worldedit, mod:forge, vanilla, file/loottable (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by AtomicStryker** [comment]
You are trying to use 1.12 templates with 1.13. They are incompatible, sadly.

The actual crash stack is unrelated to that, though.

**Comment by Bitmxp** [comment]
What's the crash stack related to then?

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/5a485a1813cbf080dc40b3079f064c859089604a an issue where i was calling client-only code for which should be a serverside mod. I fixed it, it will be in the next version.
