### ISSUE TITLE
Infernal Mobs (latest 1.15.2) Crashes on dedicated server

### ISSUE THREAD

**Issue by Nick-McKay** [AtomicStryker/atomicstrykers-minecraft-mods#361]
Don't know what the issue, is but the server works fine without infernal mobs. I've tried generating a new config, but that doesn't seem to resolve the issue.
[crash-2020-06-30_18.52.37-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/4854104/crash-2020-06-30_18.52.37-server.txt)
[2020-06-30-2.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/4854110/2020-06-30-2.log)

**Comment by AtomicStryker** [comment]
Caused by: java.lang.RuntimeException: Failed to load hierarchy member net/minecraft/client/renderer/entity/model/EntityModel
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86) ~[modlauncher-5.1.0.jar:?]
	at java.lang.Class.getSimpleName(Class.java:1309) ~[?:1.8.0_242]
	at atomicstryker.infernalmobs.common.InfernalMobsCore.checkEntityClassAllowed(InfernalMobsCore.java:311) ~[?:1.15.2.1]
	at atomicstryker.infernalmobs.common.InfernalMobsCore.isClassAllowed(InfernalMobsCore.java:291) ~[?:1.15.2.1]
	at atomicstryker.infernalmobs.common.InfernalMobsCore.processEntitySpawn(InfernalMobsCore.java:262) ~[?:1.15.2.1]
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:38) ~[?:1.15.2.1]

So there is a classloading issue, more particularly it is attempting to load a model class?? On Server? Do you have custom entities in your Infernal Mobs config, e.g. entities added by mods?

**Comment by Nick-McKay** [comment]
No, I just used the default config

**Comment by AtomicStryker** [comment]
Sorry i am on a business trip and cant add any logging right now. If you are feeling adventurous, you can try a binary search in the Infernal Mobs config (entity blacklist) to figure out which entry is causing it - copy your config at first, then remove half entities from the list. Does it still crash? If no, the error entry was in the removed half. Rinse and repeat until you know which entry (hopefully only one) is causing this.

EDIT:
Actually thats wrong, since its an entity join world event you wouldnt gain anything. Dont do it. You need a logging for which entity it is attempting to classload...

**Comment by QuarterAnimal** [comment]
For what it's worth, here's my guess:
```
[30Jun2020 18:52:35.699] [Server-Worker-14/WARN] [net.minecraft.entity.EntityType/]: Skipping Entity with id sullys_mod:goblin_witch
[30Jun2020 18:52:37.503] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent net/minecraft/client/renderer/entity/model/EntityModel for class tld/sullysmod/modid/entity/GoblinEntity$ModelGoblin in classloader cpw.mods.modlauncher.TransformingClassLoader@51de5efa on thread Thread[Server thread,5,SERVER]
[30Jun2020 18:52:37.503] [Server thread/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.EntityModel
```
Are you using the latest version of Sully's Mod? I'm not familiar with it, but glancing through the Curse forum posts I see a few complaints about server crashes around mid-June, and the error logs look a lot like yours. I also don't see any mention of a "goblin witch" among the mod's added mobs, which (witch?) leads me to believe you've got an earlier, buggy version.

**Comment by AtomicStryker** [comment]
Its probably my fault, i did not ask if you HAD modded entities on the server. Yes you do. And one of those crashes. Try removing Sullys mod and Infernal Mobs should work.
