### ISSUE TITLE
Finder Compass [1.16.1] [Forge 32.0.97] Fatal Error - Listener for event class net.minecraftforge.event.TickEvent$ClientTickEvent takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent

### ISSUE THREAD

**Issue by WHCTHBD** [AtomicStryker/atomicstrykers-minecraft-mods#365]
```
[10:15:48] [modloading-worker-6/ERROR]: Failed to create mod instance. ModID: findercompass, class atomicstryker.findercompass.common.FinderCompassMod
java.lang.IllegalArgumentException: Listener for event class net.minecraftforge.event.TickEvent$ClientTickEvent takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:236) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-3.0.3-service.jar:?]
	at atomicstryker.findercompass.common.FinderCompassMod.<init>(FinderCompassMod.java:53) ~[?:1.16.1.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2950/428475414.accept(Unknown Source) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) [?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$3041/563342464.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[10:15:48] [modloading-worker-6/ERROR]: An error occurred while dispatching event CONSTRUCT to findercompass
[10:15:48] [modloading-worker-6/FATAL]: EventBus 53 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) [eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2951/522219842.accept(Unknown Source) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) [?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$3041/563342464.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by AtomicStryker** [comment]
Its very likely an incompatibility caused by Forge updates/changes. Finder compass was built again 32.0.7 which is a bit older than this.

**Comment by AtomicStryker** [comment]
Commit https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/7f9e968071f99fd66235d08126e8cf991213b15f should fix this. I am pushing Finder Compass 1.16.1.2 to curse now.
