### ISSUE TITLE
Infernal Mobs crashing in 1.16

### ISSUE THREAD

**Issue by Raycoms** [AtomicStryker/atomicstrykers-minecraft-mods#387]
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/EntityModel
        at java.lang.Class.getDeclaringClass0(Native Method) ~[?:1.8.0_282] {}
        at java.lang.Class.getDeclaringClass(Class.java:1235) ~[?:1.8.0_282] {}
        at java.lang.Class.getEnclosingClass(Class.java:1277) ~[?:1.8.0_282] {}
        at java.lang.Class.getSimpleBinaryName(Class.java:1443) ~[?:1.8.0_282] {}
        at java.lang.Class.getSimpleName(Class.java:1309) ~[?:1.8.0_282] {}
        at atomicstryker.infernalmobs.common.InfernalMobsCore.checkEntityClassAllowed(InfernalMobsCore.java:326) ~[infernalmobs:1.16.2.1] {re:classloading}
        at atomicstryker.infernalmobs.common.InfernalMobsCore.isClassAllowed(InfernalMobsCore.java:306) ~[infernalmobs:1.16.2.1] {re:classloading}
        at atomicstryker.infernalmobs.common.InfernalMobsCore.processEntitySpawn(InfernalMobsCore.java:271) ~[infernalmobs:1.16.2.1] {re:classloading}
        at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:38) ~[infernalmobs:1.16.2.1] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_545_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) 
```

**Comment by AtomicStryker** [comment]
It would appear you have some mod installed which defines client (model) code for an entity in the entity class itself. I dont think the problem is with Infernal Mobs here.

**Comment by Raycoms** [comment]
Would it be possible to add a try/catch block where you log the entity that failed?

**Comment by AtomicStryker** [comment]
Any code line dereferencing the class (like my .getSimpleClassName above) will just crash with the same error :)

**Comment by DabbingEevee** [comment]
i have the same issue in the mineshaft and monsters modpack
