### ISSUE TITLE
Crash on 1.12.2(maybe network bug?)

### ISSUE THREAD

**Issue by MossCG** [AtomicStryker/atomicstrykers-minecraft-mods#392]
I update my bungee(waterfall) to the lastest version of support 1.17.1 because my mod server and survival1.16.5 server were in same bungee ,then sometimes there will be a crash because something stuck the main thread and the watchdog stop the server

Bungee:Waterfall b448
server:CatServer-83bb041-universal
mcversion:1.12.2
java version:jdk8u261 on server/jdk16 on bungee

fix pls

Info of server:
[11:47:43] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: PLAYER target expects a Player arg
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.RuntimeException: PLAYER target expects a Player arg
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.validateArgs(FMLOutboundHandler.java:136) ~[FMLOutboundHandler$OutboundTarget$4.class:git-CatServer-1.12.2-83bb041]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:367) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-83bb041]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.24.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:704) ~[AbstractChannelHandlerContext.class:4.1.24.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1056) ~[DefaultChannelPipeline.class:4.1.24.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:290) ~[AbstractChannel.class:4.1.24.Final]
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:392) ~[EmbeddedChannel.class:4.1.24.Final]
	at atomicstryker.infernalmobs.common.network.NetworkHelper.sendPacketToPlayer(NetworkHelper.java:108) ~[NetworkHelper.class:?]
	at atomicstryker.infernalmobs.common.network.MobModsPacket$ScheduledCode.run(MobModsPacket.java:83) ~[MobModsPacket$ScheduledCode.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[11:47:43] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Ori lost connection: Timed out

**Comment by MossCG** [comment]
after server stop responding,the watchdog infos
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: The server has stopped responding!
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: Spigot version: git-CatServer-1.12.2-83bb041 (MC: 1.12.2)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: Memory using: 1059MB/2231MB/8158MB
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: Server thread dump (Look for plugins here before reporting to Spigot!):
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: ------------------------------
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: Current Thread: Server thread
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	PID: 39 | Suspended: false | Native: false | State: RUNNABLE
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 	Stack:
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.lang.Thread.yield(Native Method)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		atomicstryker.infernalmobs.common.network.NetworkHelper.checkClassAndSync(NetworkHelper.java:165)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		atomicstryker.infernalmobs.common.network.NetworkHelper.sendPacketToPlayer(NetworkHelper.java:105)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		atomicstryker.infernalmobs.common.network.MobModsPacket$ScheduledCode.run(MobModsPacket.java:83)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.util.concurrent.FutureTask.run(Unknown Source)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.util.Util.func_181617_a(SourceFile:46)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[11:49:54] [Spigot Watchdog Thread/ERROR] [Minecraft]: 		java.lang.Thread.run(Unknown Source)

**Comment by MossCG** [comment]
no crash reports, just stop responding

**Comment by AtomicStryker** [comment]
The only theory i can offer is that a player timed out in the very moment a packet was supposed to be sent to him

[11:47:43] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Ori lost connection: Timed out

Otherwise, i don't support MC 1.12 anymore, sorry
