### ISSUE TITLE
Dynamic Lights 1.18 crashing game

### ISSUE THREAD

**Issue by anaooz** [AtomicStryker/atomicstrykers-minecraft-mods#405]
# Minecraft Crashlog - forge 38.0.17
```
Time: 21/12/2021 12:32
Description: Exception in server tick loop

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?] {}
	at atomicstryker.dynamiclights.server.GsonConfig.loadConfigWithDefault(GsonConfig.java:28) ~[dynamiclights-1.18.1.jar%2357!:1.18.1] {re:classloading}
	at atomicstryker.dynamiclights.server.DynamicLights.initConfig(DynamicLights.java:107) ~[dynamiclights-1.18.1.jar%2357!:1.18.1] {re:classloading}
	at atomicstryker.dynamiclights.server.DynamicLights.serverStarted(DynamicLights.java:99) ~[dynamiclights-1.18.1.jar%2357!:1.18.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_20_DynamicLights_serverStarted_ServerStartedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:105) ~[forge-1.18-38.0.17-universal.jar%2372!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:645) ~[client-1.18-20211130.085255-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2368!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.8.jar%2322!:?] {}
	... 15 more
```

**Comment by AtomicStryker** [comment]
Delete old dynamic lights file in minecraft config folder and let it re-generate.

**Comment by anaooz** [comment]
working fine now, thank you 🤝
