### ISSUE TITLE
Exception in Server Tick Loop (Crash)

### ISSUE THREAD

**Issue by Coraline77447** [AtomicStryker/atomicstrykers-minecraft-mods#406]
Minecraft: 1.18.1
Forge: 1.18.1, 39.0.6
Infernal Mobs: 1.18.1

Tried this a week ago after 1.18.1 came around and possibly experienced this same exact thing when I was trying all 1.18 mods (this one included) to see if they'll work for 1.18.1 (which nearly all of them do but a few and this one is one of them) but didn't report it till now when I tried Infernal Mobs again after seeing if you've updated it (which  you haven't yet..), even tho the file says 1.18.1 but I don't believe it's for 1.18.1, anyways that's not the reason for this report, the real reason is in the crash report and latest log.

Crash Report:

 ---- Minecraft Crash Report ----
// There are four lights!

Time: 12/25/21, 10:30 AM
Description: Exception in server tick loop

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!:?] {}
	at atomicstryker.infernalmobs.common.GsonConfig.loadConfigWithDefault(GsonConfig.java:29) ~[infernalmobs-1.18.1.jar%2385!:1.18.1] {re:classloading}
	at atomicstryker.infernalmobs.common.InfernalMobsCore.loadConfig(InfernalMobsCore.java:286) ~[infernalmobs-1.18.1.jar%2385!:1.18.1] {re:classloading}
	at atomicstryker.infernalmobs.common.InfernalMobsCore.initIfNeeded(InfernalMobsCore.java:161) ~[infernalmobs-1.18.1.jar%2385!:1.18.1] {re:classloading}
	at atomicstryker.infernalmobs.common.InfernalMobsCore.commonSetup(InfernalMobsCore.java:141) ~[infernalmobs-1.18.1.jar%2385!:1.18.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_18_InfernalMobsCore_commonSetup_ServerStartedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:105) ~[forge-1.18.1-39.0.6-universal.jar%23115!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:645) ~[client-1.18.1-20211210.034407-srg.jar%23111!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23111!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.8.jar%2322!:?] {}
	... 16 more

Latest Log:
[2021-12-25-1.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/7776121/2021-12-25-1.log)

**Comment by AtomicStryker** [comment]
This is a config parsing error. Delete your old (pre 1.18) infernal mobs config and let it re-generate. Keep a backup if you have to transfer settings.
