### ISSUE TITLE
Conflict with Brutal Bosses

### ISSUE THREAD

**Issue by Gaxon1** [AtomicStryker/atomicstrykers-minecraft-mods#418]
Forge 39.0.88
1.18.1

Description: Unexpected error

java.lang.ClassCastException: class java.util.concurrent.ConcurrentHashMap cannot be cast to class java.util.LinkedHashMap (java.util.concurrent.ConcurrentHashMap and java.util.LinkedHashMap are in module java.base of loader 'bootstrap')
	at atomicstryker.infernalmobs.client.InfernalMobsClient.onPreRenderGameOverlay(InfernalMobsClient.java:129) ~[infernalmobs-1.18.1.jar%23174!/:1.18.1] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.eventbus.ASMEventHandler_192_InfernalMobsClient_onPreRenderGameOverlay_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:876) ~[forge-1.18.1-39.0.76-universal.jar%23305!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:351) ~[forge-1.18.1-39.0.76-universal.jar%23305!/:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:866) ~[client-1.18.1-20211210.034407-srg.jar%23301!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23301!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23301!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23301!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.76.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by AtomicStryker** [comment]
Ah, so what happens is both Infernal Mobs and Brutal Bosses hack into a vanilla field. Brutal Bosses apparently overwrites the value with a type that is not what Infernal Mobs expects.

Go into your infernal mobs config and disable healthbars: "disableHealthBar" to true
