### ISSUE TITLE
findercompass-1.18.4 crashes.

### ISSUE THREAD

**Issue by Jeppa** [AtomicStryker/atomicstrykers-minecraft-mods#427]
Latest version 1.18.4 for MC 1.18.2 just crashes here...
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "atomicstryker.findercompass.common.CompassConfig.getOnScreenPositionWidth()" because "atomicstryker.findercompass.common.FinderCompassMod.instance.compassConfig" is null
Exit-Code: -1
```
and 
```
java.lang.NullPointerException: Cannot invoke "atomicstryker.findercompass.common.CompassConfig.getOnScreenPositionWidth()" because "atomicstryker.findercompass.common.FinderCompassMod.instance.compassConfig" is null
	at atomicstryker.findercompass.client.CompassRenderHook.updateConfigValues(CompassRenderHook.java:58) ~[findercompass-1.18.4.jar%2353!/:1.18.4] {re:classloading}
	at atomicstryker.findercompass.client.CompassRenderHook.onTick(CompassRenderHook.java:44) ~[findercompass-1.18.4.jar%2353!/:1.18.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3_CompassRenderHook_onTick_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:865) ~[forge-1.18.2-40.0.12-universal.jar%2361!/:?] {re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:359) ~[forge-1.18.2-40.0.12-universal.jar%2361!/:?] {re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1219) ~[client-1.18.2-20220228.144236-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220228.144236-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.12.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by AtomicStryker** [comment]
Hmm config not present ... do you have an old finder compass config file by any chance? Is there a config read error earlier in the log? Did you try deleting the config file and letting it regenerate?

**Comment by Jeppa** [comment]
There was an old config, but i removed it after first crash.
But without any config it's just the same crash.

Info: I'm using a custom folder for 1.18.2 mods (set in Launcher -->                 ...\.minecraft\1.18.2\). 
Mod shows up ingame... 
But when i try to join a server -> crash.
No new config is written...

Starting in default folder doesn't change anything...

**Comment by Jeppa** [comment]
PS: 
just connecting to a server -> crash ...
starting a single player world -> config is written!

Connecting to a server after default config was written, seems to work now!

After restarting the client i always need to start single player first, before i can join a server now.

**Comment by AtomicStryker** [comment]
I see, there is a hole in my config logic when joining a server that does not have Findercompass - i never tested that usecase.
This is annoying to reproduce for me .. could you try this file (rename to .jar if needed) and see if the problem is fixed
[findercompass-1.18.5.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/8428010/findercompass-1.18.5.zip)

**Comment by Jeppa** [comment]
Seems to be working now ;) Thanks!

**Comment by AtomicStryker** [comment]
Thanks for the feedback. Pushed a new version https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/5fdfe1afc698a93bd5a9b5b5ea0526c9cfecfdcd and to curse
