### ISSUE TITLE
[1.12.2] Crash when using Cubic Chunks

### ISSUE THREAD

**Issue by loquesangra** [AtomicStryker/atomicstrykers-minecraft-mods#459]
Hello =) I am reporting a crash that happens when using Cubic Chunks.

( Full log at https://f.perl.bot/raw/soivo2 )

```
java.lang.NullPointerException
	at io.github.opencubicchunks.cubicchunks.core.world.chunkloader.CubicChunkManager.onForgeChunkManagerUnforceChunk(CubicChunkManager.java:268) ~[CubicChunkManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_CubicChunkManager_onForgeChunkManagerUnforceChunk_UnforceChunkEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:859) ~[ForgeChunkManager.class:14.23.5.2860]
	at atomicstryker.minions.common.entity.EntityMinion.func_70071_h_(EntityMinion.java:306) ~[EntityMinion.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
	... 19 more
```

Probably has to do with the minions' movement.

Great mod idea by the way. Have a nice day!!

**Comment by loquesangra** [comment]
Whoops, I didn't notice you hosted all your mods here. This is for the Minions mod. Sorry!! And GitHub is half-broken on my web browser, so I can't edit the issue's title or description.

**Comment by AtomicStryker** [comment]
Hi, this appears to be crashing inside Cubic Chunks mod. This is probably a minor incompatibility issue and i see their author has already patched a workaround.

**Comment by loquesangra** [comment]
Hello!

Wow that was fast lol. I've tested the mod and it's now fully working. The only issue I found was that the master staff's lightning effect does not render properly when in very high coordinates. (Not sure if you would like to make a new issue on this, or keep this one open.) Otherwise, it's all good. Thanks for making this mod =)

**Comment by AtomicStryker** [comment]
I dont really support old versions of MC so best leave it be ;)
But good to hear your issue was solved
