### ISSUE TITLE
Infernal Mobs Neoforge 21.0.X Ticking Entity Crash

### ISSUE THREAD

**Issue by tymmanence** [AtomicStryker/atomicstrykers-minecraft-mods#514]
Like the title says, in Neoforge it seems like every enemy adjusted by Infernal Mobs throws a ticking entity error, unfortunately. I've captured 3 errors using Neruina because I was using that for testing to make sure it was every infernal mob, but I can get you a full crash report if you want. I've always loved this mod and would be happy to see it working in current versions!

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.LivingEntity net.neoforged.neoforge.event.entity.living.LivingChangeTargetEvent.getNewTarget()'
	at TRANSFORMER/infernalmobs@1.21.2NF/atomicstryker.infernalmobs.common.EntityEventHandler.onEntityLivingSetAttackTarget(EntityEventHandler.java:68)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@21.0.110-beta/net.neoforged.neoforge.common.CommonHooks.onLivingChangeTarget(CommonHooks.java:261)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.setTarget(Mob.java:243)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Creeper.setTarget(Creeper.java:170)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.start(NearestAttackableTargetGoal.java:69)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.WrappedGoal.start(WrappedGoal.java:41)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:99)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2705)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.aiStep(Mob.java:559)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.tick(Mob.java:351)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Creeper.tick(Creeper.java:161)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.mixinextras$bridge$accept$142(Level.java)
	at TRANSFORMER/neruina@2.1.0/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.wrapOperation$zzi000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:1263)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.guardEntityTick(Level.java:570)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.LivingEntity net.neoforged.neoforge.event.entity.living.LivingChangeTargetEvent.getNewTarget()'
	at TRANSFORMER/infernalmobs@1.21.2NF/atomicstryker.infernalmobs.common.EntityEventHandler.onEntityLivingSetAttackTarget(EntityEventHandler.java:68)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@21.0.110-beta/net.neoforged.neoforge.common.CommonHooks.onLivingChangeTarget(CommonHooks.java:261)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.setTarget(Mob.java:243)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.start(NearestAttackableTargetGoal.java:69)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.WrappedGoal.start(WrappedGoal.java:41)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:99)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2705)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.aiStep(Mob.java:559)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:253)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.tick(Mob.java:351)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:225)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.mixinextras$bridge$accept$142(Level.java)
	at TRANSFORMER/neruina@2.1.0/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.wrapOperation$zzi000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:1263)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.guardEntityTick(Level.java:570)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.LivingEntity net.neoforged.neoforge.event.entity.living.LivingChangeTargetEvent.getNewTarget()'
	at TRANSFORMER/infernalmobs@1.21.2NF/atomicstryker.infernalmobs.common.EntityEventHandler.onEntityLivingSetAttackTarget(EntityEventHandler.java:68)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@21.0.110-beta/net.neoforged.neoforge.common.CommonHooks.onLivingChangeTarget(CommonHooks.java:261)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.setTarget(Mob.java:243)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.target.HurtByTargetGoal.alertOther(HurtByTargetGoal.java:116)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.target.HurtByTargetGoal.alertOthers(HurtByTargetGoal.java:111)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.target.HurtByTargetGoal.start(HurtByTargetGoal.java:74)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.WrappedGoal.start(WrappedGoal.java:41)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:99)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2705)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.aiStep(Mob.java:559)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:253)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.Mob.tick(Mob.java:351)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:225)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.mixinextras$bridge$accept$142(Level.java)
	at TRANSFORMER/neruina@2.1.0/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.wrapOperation$zzi000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:1263)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.guardEntityTick(Level.java:570)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by AtomicStryker** [comment]
It's probably Neoforge changing their API. saucyexpress just pull requested an update:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/28203b69a52617654b5f53aab65c7ce81ee1d1eb

I have just pushed a new version to curse, see if that helps your problem.

**Comment by tymmanence** [comment]
Hey, thanks! Looks like it's working now, I tried it alone and then with a slew of other mods and no crashes after multiple encounters. Thanks for the quick fix and all your work! I'll report if anything comes up in the future!

**Comment by AtomicStryker** [comment]
Good to hear
