### ISSUE TITLE
Ruins  1.19.2.1 issues

### ISSUE THREAD

**Issue by Paraasoul** [AtomicStryker/atomicstrykers-minecraft-mods#527]
**Versioning**
Which version of Minecraft, which mod version, and which modloader are you using (Forge, Neoforge etc).
Some error reports don't even specify which mod has a bug...
Ruins *1.19.2.1* and im using forge 1.19.2-43.4.6. My minecraft version is 1.19.2.
![Screenshot_2024_1130_155743](https://github.com/user-attachments/assets/bb011155-b830-4a33-9538-35b1ef35d20d)

**What did you do**
What do i have to do on my end to see the problem.
I just put the ruins_config file inside the configs and launched my minecraft expecting to fix the issue but no it did NOT fix the issue.
**Expected behavior**
I expected the mod to work well with no flaws or issues on the way.
**Screenshots/Video**
If applicable, add media to help explain your problem.

**Comment by AtomicStryker** [comment]
Good report! Could have been even better with the latest.log but thats OK i can reproduce this

[30Nov2024 09:23:59.555] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: ruins, class atomicstryker.ruins.common.RuinsMod
java.lang.NoSuchMethodError: 'com.mojang.brigadier.builder.LiteralArgumentBuilder net.minecraft.commands.Commands.literal(java.lang.String)'
	at atomicstryker.ruins.common.CommandParseTemplate.<clinit>(CommandParseTemplate.java:20) ~[ruins-1.19.2.1.jar%23153!/:1.19.2.1]
	at atomicstryker.ruins.common.RuinsMod.<init>(RuinsMod.java:60) ~[ruins-1.19.2.1.jar%23153!/:1.19.2.1]

Let me check out why this doesnt happen in test runs.

**Comment by AtomicStryker** [comment]
My bad, i uploaded a jar that was not reobfuscated.

I deleted the file from curse and uploaded an obfuscated one, the problem is gone for me locally.

Thanks for reporting it.

**Comment by Paraasoul** [comment]
Alright thanks.

**Comment by DeuceWins** [comment]
I am running into the same problem, see attached file.
[latest.log](https://github.com/user-attachments/files/18157820/latest.log)

**Comment by AtomicStryker** [comment]
Make sure to download the current 1.19.2 version from curse https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system/files/all?page=1&pageSize=20

The one uploaded on November 30
