### ISSUE TITLE
CTD HashMap error at RuinsMod.onEntityEnteringChunk -- may be template related

### ISSUE THREAD

**Issue by hanleybrand** [AtomicStryker/atomicstrykers-minecraft-mods#54]
I'm seeing intermittent CTDs using MC 1.9/Forge 1.9 - 12.16.0.1816 and the logs are blaming Ruins (although it could be an intermod conflict since I have other mods) -- I have gone back and forth on suspecting that it's being caused by an old template.  I'll try removing my extra teampltes (go back to default templates) and see.

[Minecraft Crash Report](http://paste.ee/p/tnxzU)

```
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
    at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:133)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
...
```

Right before the most recent crash I saw this in the logs

```
[14:46:10] [Client thread/INFO]: [CHAT] [@: Object successfully summoned]
[14:46:35] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1575) ~[rr.class:?]
    at net.minecraft.entity.Entity.func_70039_c(Entity.java:1486) ~[rr.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:325) ~[ass.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:170) [ass.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:219) [lo.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:247) [lo.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1042) [lp.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:352) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:323) [byn.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:632) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:238) [byn.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
    at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:129) ~[ahg.class:?]
    at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:132) ~[ahh.class:?]
    at net.minecraft.entity.passive.EntityVillager.func_70014_b(EntityVillager.java:259) ~[ze.class:?]
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1548) ~[rr.class:?]
    ... 12 more
[14:46:46] [Server thread/INFO]: [@: Object successfully summoned]
[14:46:46] [Client thread/INFO]: [CHAT] [@: Object successfully summoned]
[14:47:18] blah blah blah
```

But here's [the actual crash from latest.log]

```
[14:47:46] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.EntityEvent$EnteringChunk@37a17b7c:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_77]
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458) ~[?:1.8.0_77]
    at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:133) ~[RuinsMod.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:717) [ase.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:1982) [aht.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836) [lp.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:1903) [aht.class:?]
    at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:648) [lp.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1713) [aht.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) [lp.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:238) [byn.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[14:47:46] [Server thread/ERROR]: Index: 1 Listeners:
[14:47:46] [Server thread/ERROR]: 0: NORMAL
[14:47:46] [Server thread/ERROR]: 1: ASM: atomicstryker.ruins.common.RuinsMod@21b508a0 onEntityEnteringChunk(Lnet/minecraftforge/event/entity/EntityEvent$EnteringChunk;)V
[14:47:46] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:711) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:238) ~[byn.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_77]
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458) ~[?:1.8.0_77]
    at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:133) ~[RuinsMod.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:717) ~[ase.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:1982) ~[aht.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836) ~[lp.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:1903) ~[aht.class:?]
    at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:648) ~[lp.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1713) ~[aht.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[lp.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705) ~[MinecraftServer.class:?]
    ... 4 more
[14:47:47] [Server thread/ERROR]: This crash report has been saved to: /Users/hanleybrand/multimc/instances/Forge 1.9/minecraft/crash-reports/crash-2016-03-31_14.47.46-server.txt
[14:47:47] [Server thread/INFO]: Stopping server
[14:47:47] [Server thread/INFO]: Saving players
[14:47:47] [Server thread/INFO]: Saving worlds
[14:47:47] [Server thread/INFO]: Saving chunks for level 'No abysscraft 157776747634262980'/Overworld
[14:47:47] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:527]: ---- Minecraft Crash Report ----
```

**Comment by AtomicStryker** [comment]
Looks valid. https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/8cfad336504c44a7f32b06026f6edafcf2f2a908 should take care of it. Thank you for bringing it up.

**Comment by AtomicStryker** [comment]
Update 15.8 has been pushed to my site and curse both. Try it.

**Comment by hanleybrand** [comment]
This seems to have fixed the crashes -- in older templates there are still some command blocks that aren't executing, but my guess is that the command stings aren't escaped correctly.
