### ISSUE TITLE
BattleTower crash on 1.10.2 java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that is not an Item or Block

### ISSUE THREAD

**Issue by enricotagliavini** [AtomicStryker/atomicstrykers-minecraft-mods#66]
Got this right after instaling BattleTower mod. World was created yesterday.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 27/11/16 13:39
Description: Exception in server tick loop

java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that is not an Item or Block (found : net.minecraft.util.SoundEvent at java.lang.reflect.Field.soundGolemAwaken)
	at net.minecraftforge.fml.common.registry.ObjectHolderRef.<init>(ObjectHolderRef.java:88)
	at net.minecraftforge.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:120)
	at net.minecraftforge.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:73)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-327.36.3.el7.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 128648520 bytes (122 MB) / 681050112 bytes (649 MB) up to 1431830528 bytes (1365 MB)
	JVM Flags: 1 total; -Xmx1536M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099-universal.jar) 
	UC	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099-universal.jar) 
	UC	NotEnoughItems{2.1.2.163} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.163-universal.jar) 
	UC	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UC	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UC	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UC	boatlantern{1.10.2-0.2.1} [Lantern] (boatlantern-0.2.1.jar) 
	UC	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UC	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UC	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UC	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UC	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UC	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UC	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UC	drpcore{0.1.6b} [Dark Roleplay Core] (drpcore-0.1.6b.jar) 
	UC	drpmedieval{0.1.5} [Dark Roleplay Medieval] (drpmedieval-0.1.5.jar) 
	UC	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.0.jar) 
	UC	forestry{5.2.16.328} [Forestry] (forestry_1.10.2-5.2.16.328.jar) 
	UC	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UC	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UC	journeymap{1.10.2-5.3.0} [JourneyMap] (journeymap-1.10.2-5.3.0.jar) 
	UC	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UC	minecolonies{1.10.2-0.4.1784} [MineColonies] (minecolonies-universal-1.10.2-0.4.1784.jar) 
	UC	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-416.jar) 
	UC	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UC	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UC	sgcraft{1.13.0} [SG Craft] (SGCraft-1.13.0-mc1.10.2.jar) 
	UC	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UC	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

List of installed mods:
```
$ ls mods/*
mods/Baubles-1.10.2-1.3.5.jar                       mods/CodeChickenLib-1.10.2-2.4.3.124-universal.jar      mods/inventorypets-1.10-1.4.8.2.jar                 mods/parachutemod-ng-1.10.2-1.5.2-416.jar
mods/boatlantern-0.2.1.jar                          mods/Draconic-Evolution-1.10.2-2.0.3.137-universal.jar  mods/ironchest-1.10.2-7.0.11.797.jar                mods/Railcraft_1.10.2-10.0.0.jar
mods/Botania r1.9-339.jar                           mods/drpcore-0.1.6b.jar                                 mods/jei_1.10.2-3.13.6.387.jar                      mods/Ruins-1.10.2.jar
mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar     mods/drpmedieval-0.1.5.jar                              mods/journeymap-1.10.2-5.3.0.jar                    mods/SGCraft-1.13.0-mc1.10.2.jar
mods/ChestTransporter-1.10.2-2.5.6.jar              mods/extrautils2-1.10.2-1.1.0.jar                       mods/Mantle-1.10.2-1.1.1.jar                        mods/TConstruct-1.10.2-2.5.6b.jar
mods/Chisel-MC1.10.2-0.0.7.3.jar                    mods/forestry_1.10.2-5.2.16.328.jar                     mods/minecolonies-universal-1.10.2-0.4.1784.jar     mods/Waila-1.7.0-B3_1.9.4.jar
mods/CodeChickenCore-1.10.2-2.3.5.91-universal.jar  mods/infinitylib-0.2.1.jar                              mods/NotEnoughItems-1.10.2-2.1.2.163-universal.jar  mods/Wawla-1.10.2-2.3.1.213.jar

mods/1.10.2:

mods/resources:
ruins
```

Forge version: 1.10.2-12.18.2.2099 (recommended version for 1.10.2 as of yestrday).

**Comment by enricotagliavini** [comment]
Just tried with forge 1.10.2-12.18.2.2151 and it works. If the mod is not compatible with the current recommended version of forge it might be good to add a check so the error message is clearer.

**Comment by AtomicStryker** [comment]
Keeping track of which forge versions are incompatible to each other is too much of a chore, honestly.

**Comment by enricotagliavini** [comment]
I agree, it is painful. I don't say you should test all versions, but you might on a report base like this. Kind of a compromise, at least less people have the pain of dealing with forge incompatibilities. For most users these errors are just like an alien language. I looked at the changelog of forge and saw something that sounded related. I'm no MC modder, however I know quite a few programming languages and am used to issues like this.

Also thank you for your work on MC mods, I appreciate and run some of them as you can see :)

**Comment by APolarBaer** [comment]
recommended forge has been like 2125 for a while now though? owo it was when i was working on my pack again at least

**Comment by enricotagliavini** [comment]
Is it? I see 2099 here https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html

**Comment by APolarBaer** [comment]
i guess they changed it OwO idk i probably misread what i was doing, anyways ive been running with 2125 for like 3 weeks now and its been perfect owo 
i mean yeah i still get errors but i dunno
