### ISSUE TITLE
Update Checker not Compatible with Minecraft 1.11.2

### ISSUE THREAD

**Issue by Zarepheth** [AtomicStryker/atomicstrykers-minecraft-mods#76]
The Update Checker mod, included in the Multi-Mine zip file, is not compatible with MC 1.11.2 - or pulling the two Mods out of the Zip file broke something. Anyway, this looks like some resources were not renamed to meet the 1.11.2 naming requirements.

[23:12:11] [Client thread/DEBUG] [FML/]: Examining file UpdateCheckerMod-1.11.jar for potential mods
[23:12:11] [Client thread/TRACE] [FML/]: Located mcmod.info file in file UpdateCheckerMod-1.11.jar
[23:12:11] [Client thread/DEBUG] [FML/]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (atomicstryker.updatecheck.common.UpdateCheckMod) - loading
[23:12:11] [Client thread/WARN] [FML/]: ****************************************
[23:12:11] [Client thread/WARN] [FML/]: * The modid AS_UpdateCheck is not the same as it's lowercase version. Lowercasing is enforced in 1.11
[23:12:11] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:145)
[23:12:11] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[23:12:11] [Client thread/WARN] [FML/]: *  at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
[23:12:11] [Client thread/WARN] [FML/]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:12:11] [Client thread/WARN] [FML/]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[23:12:11] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:86)...
[23:12:11] [Client thread/WARN] [FML/]: ****************************************
[23:12:11] [Client thread/ERROR] [FML/]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:86) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:105) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:393) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:533) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: The modid AS_UpdateCheck is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:146) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128) ~[FMLModContainer.class:?]
	... 20 more

**Comment by AtomicStryker** [comment]
Better title: Mods for 1.11 incompatible with 1.11.2. Mojang conspiracy?

**Comment by Zarepheth** [comment]
Maybe I'm crazy, but for some reason, I thought 1.11.2 (and 1.11.1) should be backward compatible with mods for 1.11...

**Comment by AtomicStryker** [comment]
The accurate answer is "mostly-ish"
