### ISSUE TITLE
1.11.2 - Stalker Creepers - isSeenByTarget Crash

### ISSUE THREAD

**Issue by JonnyBrando** [AtomicStryker/atomicstrykers-minecraft-mods#88]
Crash logs are attached.

MC 1.11.2
Forge 13.20.0.2252
Optifine 1.11.2 HD U B8 PRE

[spoiler]java.lang.NoSuchMethodError: atomicstryker.stalkercreepers.common.EntityAIHelperStalker.isSeenByTarget(Lnet/minecraft/entity/EntityLivingBase;)Z
	at net.minecraft.entity.ai.EntityAICreeperSwell.func_75250_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:895)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:41)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:161)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.EntityAICreeperSwell.func_75250_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:895)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:41)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:161)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.EntityCreeper)
	Entity ID: 239
	Entity Name: Creeper
	Entity's Exact location: 38.27, 51.00, 258.50
	Entity's Block location: World: (38,51,258), Chunk: (at 6,3,2 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1747)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['sprinkles'/420, l='Test', x=39.99, y=51.00, z=259.83]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 7661900886522797728
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (56,64,236), Chunk: (at 8,4,12 in 3,14; contains blocks 48,0,224 to 63,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17364 game time, 17364 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31190 (now: false), thunder time: 26287 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)[/spoiler]

[crash-2017-02-26_14.18.06-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/802199/crash-2017-02-26_14.18.06-server.txt)

[fml-client-latest.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/802201/fml-client-latest.txt)

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/4b77919f70eebeb68ac8772ec66e94d8e58a6542

this should fix that, please check

(i pushed updated files to my website and curse, also github.io)

**Comment by JonnyBrando** [comment]
Thanks for the update, AtomicStryker!

I'll check it out this afternoon with my daughter :).

**Comment by JonnyBrando** [comment]
FYI, your Curse didn't update. Last update Jan 7, 2016.

GITHUB.IO = 10.6KB
Curse = 8.67KB
AtomicStryker.net = ?? (can't get through adfly at work :P)

**Comment by AtomicStryker** [comment]
Github.io and my site are identical. Curse needs a little while to update
