### ISSUE TITLE
Simply Hax: Inconsistent crash w/ NullPointerException when loading world

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#89]
Sometimes the game will crash with a NullPointerException when loading a world. It seems to be with the onTick method.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-81.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  ForgelinPlugin (Forgelin-1.3.1.jar)
  SHLoadingPlugin (ScalingHealth-1.11-1.0.3-36.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/5/17 5:35 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at atomicstryker.simplyhax.SimplyHaxFlying.onTick(SimplyHaxFlying.java:118)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_164_SimplyHaxFlying_onTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:381)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:291)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at atomicstryker.simplyhax.SimplyHaxFlying.onTick(SimplyHaxFlying.java:118)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_164_SimplyHaxFlying_onTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:381)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:291)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 614
	Entity Name: luckyp3616
	Entity's Exact location: 9.01, 63.00, -10.74
	Entity's Block location: World: (9,63,-11), Chunk: (at 9,3,5 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:329)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@810ad4e
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.9.13-VANILLA+
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1210197392 bytes (1154 MB) / 2093809664 bytes (1996 MB) up to 21421162496 bytes (20428 MB)
	JVM Flags: 4 total; -Xms2G -Xmx20G -XX:+UseConcMarkSweepGC -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 Optifine OptiFine_1.11.2_HD_U_B7 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAAAAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAAAAAAA	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAAAAAAA	quark{r1.2-81} [Quark] (Quark-r1.2-81.jar) 
	UCHIJAAAAAAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAAAAAAA	cyclicmagic{1.1.3} [Cyclic] (Cyclic-1.11.2-1.1.3.jar) 
	UCHIJAAAAAAAAA	forgelin{1.3.0} [Forgelin] (Forgelin-1.3.1.jar) 
	UCHIJAAAAAAAAA	hammercore{1.2.6} [Hammer Core] (HammerCore_1.11.2-1.2.6.jar) 
	UCHIJAAAAAAAAA	healthbar{1.0.5} [Health Bar] (HealthBar-1.11-1.0.5b-20.jar) 
	UCHIJAAAAAAAAA	itemeditor{1.11.x-0.1.0.1} [Item Editor GUI] (itemeditor-1.11.x-0.1.0.1.jar) 
	UCHIJAAAAAAAAA	jei{4.2.7.240} [Just Enough Items] (jei_1.11.2-4.2.7.240.jar) 
	UCHIJAAAAAAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAAAAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAAAAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJAAAAAAAAA	leveluphp{1.0.1} [Level Up HP] (leveluphp-1.11-1.0.1.jar) 
	UCHIJAAAAAAAAA	playerstats2{13r} [Player Stats 2] (PlayerStats2_1.11.2-13r.jar) 
	UCHIJAAAAAAAAA	reccomplex{1.2.9.1} [Recurrent Complex] (RecurrentComplex-1.2.9.1.jar) 
	UCHIJAAAAAAAAA	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAAAAAAA	silentlib{1.2.0} [Silent Lib] (SilentLib-1.11-1.2.0-30.jar) 
	UCHIJAAAAAAAAA	scalinghealth{1.0.3} [Scaling Health] (ScalingHealth-1.11-1.0.3-36.jar) 
	UCHIJAAAAAAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAAAAAAA	silentgems{2.2.9} [Silent's Gems] (SilentsGems-1.11-2.2.9-114.jar) 
	UCHIJAAAAAAAAA	sgextraparts{1.2.4} [Silent's Gems: Extra Parts] (SGExtraParts-1.11-1.2.4-12.jar) 
	UCHIJAAAAAAAAA	simpledimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.11-1.3.jar) 
	UCHIJAAAAAAAAA	simplyhaxentitydump{1.11} [Simply Hax Entity Dump] (SimplyHax-1.11.2.jar) 
	UCHIJAAAAAAAAA	simplyhaxflying{1.11} [Simply Hax Flying] (SimplyHax-1.11.2.jar) 
	UCHIJAAAAAAAAA	stacksize{1.0} [Stacksize Mod] (stacksize-1.11.2-1.0.jar) 
	UCHIJAAAAAAAAA	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCHIJAAAAAAAAA	torohealthmod{1.11.2-10} [ToroHealth Damage Indicators] (torohealth-1.11.2-10.jar) 
	UCHIJAAAAAAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-81.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.2.1.jar)
  
ForgelinPlugin (Forgelin-1.3.1.jar)
  
SHLoadingPlugin (ScalingHealth-1.11-1.0.3-36.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['luckyp3616'/614, l='New World', x=9.01, y=63.00, z=-10.74]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 17.0.0
	OpenGlRenderer: Gallium 0.4 on AMD TONGA (DRM 3.8.0 / 4.9.13-VANILLA+, LLVM 3.9.1)
	OpenGlVendor: X.Org
	CpuCount: 8

**Comment by AtomicStryker** [comment]
Thanks for the report, fixed in https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/88a3116b2da5e15e78897bb9303a067f6be0145d
