### ISSUE TITLE
[1.7.10] Crash, while creating a new World

### ISSUE THREAD

**Issue by DaNeubi** [AtomicStryker/atomicstrykers-minecraft-mods#99]
Hey, wanna report a Bug.

This is the Error Messsage:
```
`Unreported exception thrown!
java.lang.NoSuchMethodError: atomicstryker.dynamiclights.client.DynamicLights.globalLightsOff()Z
	at fiskfille.lightsabers.common.event.CommonEventHandlerDL.onTick(CommonEventHandlerDL.java:42) ~[CommonEventHandlerDL.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_55_CommonEventHandlerDL_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[00:54:12] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/25/17 12:54 AM
Description: Unexpected error

java.lang.NoSuchMethodError: atomicstryker.dynamiclights.client.DynamicLights.globalLightsOff()Z
	at fiskfille.lightsabers.common.event.CommonEventHandlerDL.onTick(CommonEventHandlerDL.java:42)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_55_CommonEventHandlerDL_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`
```
I'm using these Mods:
pretty sure one of these causes this, because in an earlier state I didn't got this problem.

```
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	securitycraft{v1.8.2.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.1.jar) 
	UCHIJAAAA	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.8} [Storage Drawers] (StorageDrawers-1.7.10-1.10.8.jar) 
	UCHIJAAAA	dendrology{1.7.10-1.6.4} [Ancient Trees] (AncientTrees-1.7.10-1.6.4.jar) 
	UCHIJAAAA	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
	UCHIJAAAA	AntiqueAtlasOverlay{1.2} [Antique Atlas Overlay] (AntiqueAtlasOverlay-1.7.10-1.2.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.21} [BuildCraft] (buildcraft-7.1.21-core.jar) 
	UCHIJAAAA	voltzengine{1.2.3.41} [Voltz Engine] (VoltzEngine-1.7.10-1.2.3b41.jar) 
	UCHIJAAAA	assemblyline{0.5.3.84} [Assembly Line] (Assembly-Line-1.7.10-0.5.3b84.jar) 
	UCHIJAAAA	BetterFoliage{2.0.15} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.15.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.21} [BC Robotics] (buildcraft-7.1.21-robotics.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.21} [BC Silicon] (buildcraft-7.1.21-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.21} [BC Transport] (buildcraft-7.1.21-transport.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-3.jar) 
	UCHIJAAAA	deathquotes{1.0.1} [Death Quotes] (DeathQuotes-1.2.0-mc1.7.10-forge.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.1_1.7.10.jar) 
	UCHIJAAAA	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.7.10.jar) 
	UCHIJAAAA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJAAAA	dsurround{1.0.5.11} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.11.jar) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAAAA	FoodExpansion{1.0} [Food Expansion] (FoodExpansion1.1.1-mc1.7.10.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.129} [Logistics Pipes] (logisticspipes-0.9.3.129.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	militarybasedecor{0.0.1.129} [Military Base Decor] (MilitaryBaseDecor-1.7.10-0.0.1b129.jar) 
	UCHIJAAAA	mobcages{1.1} [MobCages] (mobcages-1.7.10-1.2.jar) 
	UCHIJAAAA	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCHIJAAAA	Monoblocks{1.10.39} [§1M§2o§3n§4o§5b§6l§7o§8c§9k§as] (Monoblocks-1.10.39.jar) 
	UCHIJAAAA	MonoblocksMultipart{1.10.39} [MonoblocksMultipart] (Monoblocks-1.10.39.jar) 
	UCHIJAAAA	morematerials{0.9.20150214.0} [More Materials] (morematerials-0.9.20150615.0-MC1.7-20150621.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	Mystcraft{0.12.3.03} [Mystcraft] (mystcraft-1.7.10-0.12.3.03.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	openmodularturrets{2.2.10-237} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.10-237.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	signposts{1.1.0} [Sign-Posts] (signposts-1.7.10-1.1.0.jar) 
	UCHIJAAAA	SilentGems{1.3.14} [Silent's Gems] (SilentGems-1.7.10-1.3.14-172.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJAAAA	vending{1.2.3} [vending] (vending-v1.2.3.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHIJAAAA	WallpaperCraft{1.7.10} [WallpaperCraft] (WallpaperCraft-1.7.10-1.03.jar) 
	UCHIJAAAA	ae2wct{1.7.10-rv3-1.8.7.4b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	List of loaded APIs: 
		* ae2wct|API (1.7.10-rv3-1.8.6b) from WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b.jar
		* antiqueatlasapi (5.1) from antiqueatlas-1.7.10-4.2.10.jar
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.21-core.jar
		* BuildCraftAPI|tools (1.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.21-core.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.2) from OpenModularTurrets-1.7.10-2.2.10-237.jar
		* CoFHAPI|block (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|core (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|energy (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|item (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.39_beta.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CoFHLib|audio (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|container (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|render|particle (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|util (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CoFHLib|util|helpers (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|util|position (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|world (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CoFHLib|world|feature (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.2.1-185.jar
		* CSLib|API (0.3.0) from Decocraft-2.4.1_1.7.10.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* GardenCoreAPI (1.0.0) from GardenStuff-1.7.10-1.7.0.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.7.7.jar
		* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.406.jar
		* Mystcraft|API (0.1) from mystcraft-1.7.10-0.12.3.03.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0-122.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.6.jar
		* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.7.7.jar
		* SecurityCraftAPI (1.2.1) from [1.7.10] SecurityCraft v1.8.2.1.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.8.jar
		* VoltzEngineAPI (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|crafting-items (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|data (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|energy (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|energy-items (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|event (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|explosive-items (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|explosives (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|items (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|recipe (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|tile (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|tools (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* VoltzEngineAPI|weapons (0.11.0) from VoltzEngine-1.7.10-1.2.3b41.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
```

Enclosed there's the full log.

Hope with this I can help you making your Mod even greater :)

Greetings

DaNeubi
[2017-04-25-7.log.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/953418/2017-04-25-7.log.zip)

**Comment by DaNeubi** [comment]
I'm not to 80% sure this error is caused because of the Advanced Lightsabers Mod.

**Comment by AtomicStryker** [comment]
You are using the "modded" dynamic lights version 1.3.9a which wasn't actually made by me. That's your problem, the lightsabers mod doesnt support whatever changes were made to the API.

**Comment by DaNeubi** [comment]
Thanks for that info, didn't know :)
